
bin:
  blast2bam: /gpfs/projects/bsc83/utils/Blast2Bam/bin/blast2bam

ref:
  fa_ver: 'hg38'
  fa_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/GRCh38.p14.genome.fa.gz
  fa: /gpfs/projects/bsc83/Data/assemblies/GRCh38.p14/GRCh38.p14.genome.fa
  mmi: ref/ref.mmi

  gtf_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v44.chr_patch_hapl_scaff.annotation.gtf.gz
  gtf: /gpfs/projects/bsc83/Data/gene_annotations/gencode/v44/gencode.v44.chr_patch_hapl_scaff.annotation.gtf
  junc_bed: /gpfs/projects/bsc83/Data/gene_annotations/gencode/v44/modified/gencode.v44.chr_patch_hapl_scaff.annotation_transcriptlevel.bed

  linker_5_fa: snakemake/ref/linker_5.fa

data:
  # raw:
  #   fq: data/raw/{sample}.fq
  #   fa: data/raw/{sample}.fa
  duplex:
    index: data/duplex/{sample}.bam.bai
    bam: data/duplex/{sample}.bam
    fastq: data/duplex/{sample}/{sample}.fastq
    fa: data/duplex/{sample}.fa
  split:
    fastqdir1: data/duplex/{sample}
    outdir1: data/split/{sample}_1step/
    mockout1: data/split/mock1_{sample}
    mockout2: data/split/mock2_{sample}
    mockout3: data/split/mock3_{sample}
    multiout: data/split/{sample}_postsplitting/
    outdir2: data/split/{sample}_2step/
    dirroot: data/split/{sample}
    fastq_split: data/split/{sample}_postsplitting/splitReads.fastq.gz


    #outsplit1_2: data/split/{sample}_1step/split_multiple_times.pkl
    #outsplit1_3: data/split/{sample}_1step/unedited.pkl

    #fastqdir2: data/split/{sample}_1step
    # outsplit2_1: data/split/{sample}_2step/edited.pkl
    # outsplit2_2: data/split/{sample}_2step/split_multiple_times.pkl
    # outsplit2_3: data/split/{sample}_2step/unedited.pkl

    # multisplitsID1: data/split/{sample}_1step/{sample}/detected_multiSPLIT_IDs.txt
    # multisplitsID2: data/split/{sample}_2step/{sample}/detected_multiSPLIT_IDs.txt
    # fastq_multisplit: data/split/{sample}_2step/multiSplitReads.fastq.gz

  blast:
      db: data/blast/5_linker_db
      nhr: data/blast/5_linker_db.nhr
      nin: data/blast/5_linker_db.nin
      nsq: data/blast/5_linker_db.nsq

      xml: data/blast/{sample}.xml
      sam: data/blast/{sample}.sam
      sam_filt: data/blast/{sample}_filt.sam
      bam: data/blast/{sample}.bam
      bam_sort: data/blast/{sample}_sorted.bam
      bam_ind: data/blast/{sample}_sorted.bam.bai

  umi:
    umis: data/umi/{sample}_extracted_UMI.tsv
    fa: data/umi/{sample}_with_extracted_UMI.fasta

  minimap:
    sam: data/minimap/{sample}.sam
    sam_filt: data/minimap/{sample}_filt.sam
    bam: data/minimap/{sample}.bam
    bam_sort: data/minimap/{sample}_sorted.bam
    bam_ind: data/minimap/{sample}_sorted.bam.bai
