bin:
  blast2bam: /gpfs/projects/bsc83/utils/Blast2Bam/bin/blast2bam

ref:
  fa_ver: 'hg38'
  fa_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/GRCh38.p14.genome.fa.gz
  fa: /gpfs/projects/bsc83/Data/assemblies/gencode/GRCh38.p14/GRCh38.p14.genome.fa
  mmi: ref/ref.mmi

  gtf_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v44.chr_patch_hapl_scaff.annotation.gtf.gz
  gtf: /gpfs/projects/bsc83/Data/gene_annotation/gencode/release_44/gencode.v44.chr_patch_hapl_scaff.annotation.gtf
  junc_bed: /gpfs/projects/bsc83/Data/gene_annotation/gencode/release_44/modified/gencode.v44.chr_patch_hapl_scaff.annotation_transcriptlevel.bed

  linker_5_fa: ref/linker_5.fa

data:
  raw:
    fq: data/raw/{sample}.fq
    fa: data/raw/{sample}.fa
  duplex:
    sam: data/duplex/{sample}.sam
    fastq: data/duplex/{sample}.fq
    fa: data/duplex/{sample}.fa
  split:
    outsplit1_ONT_CapLinker: data/split/{sample}_1step/{sample}.fq.gz
    outsplit1.1: data/split/{sample}_1step/{sample}/edited.pkl
    outsplit1.2: data/split/{sample}_1step/{sample}/split_multiple_times.pkl
    outsplit1.3: data/split/{sample}_1step/{sample}/unedited.pkl

    outsplit2_CapLinker: data/split/{sample}_2step/{sample}.fq.gz
    outsplit2.1: data/split/{sample}_2step/{sample}/edited.pkl
    outsplit2.2: data/split/{sample}_2step/{sample}/split_multiple_times.pkl
    outsplit2.3: data/split/{sample}_2step/{sample}/unedited.pkl

    multisplitsID1: data/split/{sample}_1step/{sample}/detected_multiSPLIT_IDs.txt
    multisplitsID2: data/split/{sample}_2step/{sample}/detected_multiSPLIT_IDs.txt
    fastq_split: data/split/{sample}_2step/splitReads.fastq.gz
    fastq_multisplit: data/split/{sample}_2step/multiSplitReads.fastq.gz

  blast:
      db: data/blast/5_linker_db
      nhr: data/blast/5_linker_db.nhr
      nin: data/blast/5_linker_db.nin
      nsq: data/blast/5_linker_db.nsq

      xml: data/blast/{sample}.xml
      sam: data/blast/{sample}.sam
      sam_filt: data/blast/{sample}_filt.sam
      bam: data/blast/{sample}.bam
      bam_sort: data/blast/{sample}_sorted.bam
      bam_ind: data/blast/{sample}_sorted.bam.bai

  umi:
    umis: data/umi/{sample}_extracted_UMI.tsv
    fa: data/umi/{sample}_with_extracted_UMI.fasta

  minimap:
    sam: data/minimap/{sample}.sam
    sam_filt: data/minimap/{sample}_filt.sam
    bam: data/minimap/{sample}.bam
    bam_sort: data/minimap/{sample}_sorted.bam
    bam_ind: data/minimap/{sample}_sorted.bam.bai
