params:
    duplex_sep: ':'
    umi_sep: '_'

bin:
  blast2bam: /gpfs/projects/bsc83/utils/Blast2Bam/bin/blast2bam

ref:
  fa_ver: 'hg38'
  fa_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/GRCh38.p14.genome.fa.gz
  fa: /gpfs/projects/bsc83/Data/assemblies/gencode/GRCh38.p14/GRCh38.p14.genome.fa
  mmi: ref/ref.mmi

  gtf_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v44.chr_patch_hapl_scaff.annotation.gtf.gz
  gtf: /gpfs/projects/bsc83/Data/gene_annotation/gencode/release_44/gencode.v44.chr_patch_hapl_scaff.annotation.gtf
  junc_bed: /gpfs/projects/bsc83/Data/gene_annotation/gencode/release_44/modified/gencode.v44.chr_patch_hapl_scaff.annotation_transcriptlevel.bed
  gt_map: ref/gt_map.tsv

  linker_5_fa: ref/linker_5.fa

data:
  raw:
    fq: data/raw/{sample}.fq
    fa: data/raw/{sample}.fa
  duplex:
      sam: data/duplex/{sample}.sam
      read_ids: data/duplex/{sample}_read_ids.txt
      fq: data/duplex/{sample}.fq.gz
      fa: data/duplex/{sample}.fa
  blast:
      db: data/blast/5_linker_db
      nhr: data/blast/5_linker_db.nhr
      nin: data/blast/5_linker_db.nin
      nsq: data/blast/5_linker_db.nsq

      xml: data/blast/{sample}.xml
      sam: data/blast/{sample}.sam
      sam_filt: data/blast/{sample}_filt.sam
      sam_filt_2: data/blast/{sample}_filt2.sam
      bam: data/blast/{sample}.bam
      bam_sort: data/blast/{sample}_sorted.bam
      bam_ind: data/blast/{sample}_sorted.bam.bai
  umi:
    umis: data/umi/{sample}_extracted_UMI.tsv
    fa: data/umi/{sample}_with_extracted_UMI.fasta
    read_ids: data/umi/{sample}_read_ids.txt
    no_umi_read_ids: data/umi/{sample}_no_umi_read_ids.txt

  minimap:
    sam: data/minimap/{sample}.sam
    sam_filt: data/minimap/{sample}_filt.sam
    bam: data/minimap/{sample}.bam
    bam_sort: data/minimap/{sample}_sorted.bam
    bam_ind: data/minimap/{sample}_sorted.bam.bai

  umi_dedupe:
    bam: data/umi_dedupe/{sample}.bam
    log: data/umi_dedupe/{sample}.log
